update test workflow

diff --git a/.github/workflows/build_test.yml b/.github/workflows/build_test.yml
--- a/.github/workflows/build_test.yml
+++ b/.github/workflows/build_test.yml
@@ -34,6 +34,16 @@ jobs:
           restore-keys: |
             ${{ runner.os }}-maven
 
+      - name: Check if Coveralls Token is Set
+        run: |
+          if [[ -z "${{ secrets.COVERALLS_REPO_TOKEN }}" ]]; then
+            echo "ERROR: COVERALLS_REPO_TOKEN is not set!"
+            exit 1
+          else
+            echo "COVERALLS_REPO_TOKEN is set."
+          fi
+
+
       - name: Build Backend with Maven
         run: mvn clean install
 
@@ -41,4 +51,6 @@ jobs:
         run: mvn verify
 
       - name: Upload Coverage to Coveralls
-        run: mvn coveralls:report -DrepoToken=${{ secrets.COVERALLS_REPO_TOKEN }}
+        run: mvn coveralls:report
+        env:
+          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
